#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Clean polyMesh folder and time directories only

rm -rf constant/polyMesh
rm -rf 0.* *[1-9]*
rm -f log.* 2>/dev/null

#------------------------------------------------------------------------------
